# moflextab.py. This file automatically created by PLY (version 3.0). Don't edit!
_tabversion   = '3.0'
_lextokens    = {'DT_UINT8': 1, 'DISABLEOVERRIDE': 1, 'DT_STR': 1, 'DT_SINT64': 1, 'octalValue': 1, 'stringValue': 1, 'decimalValue': 1, 'DT_DATETIME': 1, 'REF': 1, 'charValue': 1, 'NULL': 1, 'REFERENCE': 1, 'TRUE': 1, 'TOSUBCLASS': 1, 'DT_REAL64': 1, 'TRANSLATABLE': 1, 'DT_UINT32': 1, 'PARAMETER': 1, 'ENABLEOVERRIDE': 1, 'CLASS': 1, 'ASSOCIATION': 1, 'SCHEMA': 1, 'DT_BOOL': 1, 'DT_UINT16': 1, 'floatValue': 1, 'DT_SINT16': 1, 'AS': 1, 'DT_SINT32': 1, 'binaryValue': 1, 'PRAGMA': 1, 'SCOPE': 1, 'FLAVOR': 1, 'DT_CHAR16': 1, 'DT_REAL32': 1, 'DT_SINT8': 1, 'FALSE': 1, 'QUALIFIER': 1, 'DT_UINT64': 1, 'OF': 1, 'hexValue': 1, 'METHOD': 1, 'INSTANCE': 1, 'IDENTIFIER': 1, 'INDICATION': 1, 'RESTRICTED': 1, 'PROPERTY': 1, 'ANY': 1}
_lexreflags   = 0
_lexliterals  = '#(){};[],$:='
_lexstateinfo = {'INITIAL': 'inclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_COMMENT>//.*)|(?P<t_MCOMMENT>/\\*(.|\\n)*?\\*/)|(?P<t_IDENTIFIER>([a-zA-Z_]|(([\\xC2-\\xDF][\\x80-\\xBF])|(\\xE0[\\xA0-\\xBF][\\x80-\\xBF])|([\\xE1-\\xEC][\\x80-\\xBF][\\x80-\\xBF])|(\\xED[\\x80-\\x9F][\\x80-\\xBF])|([\\xEE-\\xEF][\\x80-\\xBF][\\x80-\\xBF])|(\\xF0[\\x90-\\xBF][\\x80-\\xBF][\\x80-\\xBF])|([\\xF1-\\xF3][\\x80-\\xBF][\\x80-\\xBF][\\x80-\\xBF])|(\\xF4[\\x80-\\x8F][\\x80-\\xBF][\\x80-\\xBF])))([0-9a-zA-Z_]|(([\\xC2-\\xDF][\\x80-\\xBF])|(\\xE0[\\xA0-\\xBF][\\x80-\\xBF])|([\\xE1-\\xEC][\\x80-\\xBF][\\x80-\\xBF])|(\\xED[\\x80-\\x9F][\\x80-\\xBF])|([\\xEE-\\xEF][\\x80-\\xBF][\\x80-\\xBF])|(\\xF0[\\x90-\\xBF][\\x80-\\xBF][\\x80-\\xBF])|([\\xF1-\\xF3][\\x80-\\xBF][\\x80-\\xBF][\\x80-\\xBF])|(\\xF4[\\x80-\\x8F][\\x80-\\xBF][\\x80-\\xBF])))*)|(?P<t_newline>\\n+)|(?P<t_stringValue>"([^"\\\\\\n\\r]|([\\\\](([bfnrt\'"\\\\])|(x[0-9a-fA-F]{1,4}))))*")|(?P<t_floatValue>[+-]?[0-9]*\\.[0-9]+([eE][+-]?[0-9]+)?)|(?P<t_hexValue>[+-]?0[xX][0-9a-fA-F]+)|(?P<t_decimalValue>[+-]?([1-9][0-9]*|0))|(?P<t_binaryValue>[+-]?[01]+[bB])|(?P<t_octalValue>[+-]?0[0-7]+)', [None, ('t_COMMENT', 'COMMENT'), ('t_MCOMMENT', 'MCOMMENT'), None, ('t_IDENTIFIER', 'IDENTIFIER'), None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, ('t_newline', 'newline'), (None, 'stringValue'), None, None, None, None, None, (None, 'floatValue'), None, (None, 'hexValue'), (None, 'decimalValue'), None, (None, 'binaryValue'), (None, 'octalValue')])]}
_lexstateignore = {'INITIAL': ' \r\t'}
_lexstateerrorf = {'INITIAL': 't_error'}
