# Config file for the pyup.io Python update service.
# See https://pyup.io/docs/configuration/ for all available options

# Global option for selection of the kinds of updates
# default: all
# allowed: all, insecure, False
update: insecure

# Global option for pinning unpinned dependencies
# default: True
# allowed: True, False
pin: False

# Search for requirement files
# default: True
# allowed: True, False
search: False

# Specify requirement files by hand, default is empty
# default: empty
# allowed: list
# The list items are sub-options: update, pin
# Unspecified sub-options are inherited from the global options
requirements:
  - requirements.txt:
  - dev-requirements.txt:
  - rtd-requirements.txt:
  - minimum-constraints.txt:
    pin: True

# Add a label to pull requests created by the pyup bot.
# Default is no label (empty).
label_prs: "review needed"

# Assign users to pull requests created by the pyup bot.
# Default is no assigned user (empty).
assignees:
 - andy-maier

# Branch prefix used for pull requests created by the pyup bot.
# Default: pyup-
branch_prefix: pyup/
