# Safety policy file for packages needed for installation
# Docs: https://docs.safetycli.com/safety-docs/administration/safety-policy-files
#
# Generally package vulnerabilites listed in the ignore-vulnerabilities
# list below are there because:
# 1. There is no release that resolves the vulnerability.  In this case, there
#    should also be an expire entry to remind the pywbem team to recheck
# 2. The required version of a package to resolve the issue is not available
#    for all of the python version supported by pywbem. In that case, the
#    vulnerability will remain ignored until such time as the versions of
#    python that cannot support the required version of the package are no
#    longer supported by pywbem.

# Configuration for the 'safety scan' command
version: '3.0'

scanning-settings:
  max-depth: 1
  exclude:
    - dev-requirements.txt
    - test-requirements.txt
  include-files:
    - path: minimum-constraints-install.txt
      file-type: requirements.txt
  system:
    targets: []

report:
  dependency-vulnerabilities:
    enabled: true
    auto-ignore-in-report:
      python:

        # Ignore dependencies found in the current Python environment
        environment-results: false

        # Ignore unpinned packages in requirements files
        unpinned-requirements: false

      cvss-severity: []

      # List of specific vulnerabilities to ignore.
      # {id}:                 # vulnerability ID
      #     reason: {text}    # optional: Reason for ignoring it
      #     expires: {date}   # optional: Date when this ignore will expire
      vulnerabilities:
        67599:
          reason: Disputed issue in pip version 23.3 - No known fix
          expires: '2099-01-01'
        90553:
          reason: Fixed requests version 2.33.0 requires Python>=3.10 and is used there
          expires: '2099-01-01'

fail-scan-with-exit-code:
  dependency-vulnerabilities:
    enabled: true
    fail-on-any-of:
      cvss-severity:
        - high
        - critical
        - medium
        - low
      exploitability:
        - high
        - critical
        - medium
        - low

security-updates:
  dependency-vulnerabilities:
    auto-security-updates-limit:
      - patch

installation:
  default-action: allow
  audit-logging:
    enabled: true
  allow:
    packages: []
    vulnerabilities: {}
  deny:
    packages: {}
    vulnerabilities:
      warning-on-any-of:
        cvss-severity: []
      block-on-any-of:
        cvss-severity: []
