# Safety policy file for packages needed for installation
# For documentation, see https://docs.pyup.io/docs/safety-20-policy-file
#
# Generally package vulnerabilites listed in the ignore-vulnerabilities
# list below are there because:
# 1. There is no release that resolves the vulnerability.  In this case, there
#    should also be an expire entry to remind the pywbem team to recheck
# 2. The required version of a package to resolve the issue is not available
#    for all of the python version supported by pywbem. In that case, the
#    vulnerability will remain ignored until such time as the versions of
#    python that cannot support the required version of the package are no
#    longer supported by pywbem.
#
# The way to see python version limitations for package versions
#    as defined for pywbem is to filter the file minimum-constraints.txt
#    for the package name. Multiple entries for same package name imply
#    different minimum versions for different python releases.

# Configuration for the 'safety check' command
security:

    # Ignore certain severities.
    # A number between 0 and 10, with the following significant values:
    # - 9: ignore all vulnerabilities except CRITICAL severity
    # - 7: ignore all vulnerabilities except CRITICAL & HIGH severity
    # - 4: ignore all vulnerabilities except CRITICAL, HIGH & MEDIUM severity
    ignore-cvss-severity-below: 0

    # Ignore unknown severities.
    # Should be set to False.
    ignore-cvss-unknown-severity: False

    # List of specific vulnerabilities to ignore.
    # {id}:                 # vulnerability ID
    #     reason: {text}    # optional: Reason for ignoring it. Will be reported in the Safety reports
    #     expires: {date}   # optional: Date when this ignore will expire
    ignore-vulnerabilities:
        38765:
            reason: pip v 10.0.1l We want to test install with minimum pip versions.
        39611:
            reason: PyYAML full_load method or FullLoader is not used
        40291:
            reason: Fixed Pip version requires Python>=3.6 and is used there
        42559:
            reason: Fixed Pip version requires Python>=3.6 and is used there; Pip is not shipped with this package
        43975:
            reason: Fixed Urllib3 versions are excluded by requests
        51499:
            reason: Fixed Wheel version requires Python>=3.7 and is used there; Risk is on Pypi side
        52365:
            reason: Fixed Certifi version requires Python>=3.6 and is used there
        52495:
            reason: Fixed Setuptools version requires Python>=3.7 and is used there; Risk is on Pypi side
        58755:
            reason: Fixed requests version 2.31.0 requires Python>=3.7 and is used there
        59956:
            reason: Fixed certifi version 2023.07.22 requires Python>=3.6 and is used there
        61601:
            reason: Fixed urllib3 version 1.26.17 requires Python>=3.6 and is used there
        61893:
            reason: Fixed urllib3 version 1.26.18 requires Python>=3.6 and is used there
        62044:
            reason: Fixed pip version 23.3 requires Python>=3.7 and is used there
        64227:
            reason: Jinja2, ver 3.1.3 fixes scripting vulnerability, requires Python >= 3.7

    # Continue with exit code 0 when vulnerabilities are found.
    continue-on-vulnerability-error: False
