# Safety policy file for packages needed for development
# Docs: https://docs.safetycli.com/safety-docs/administration/safety-policy-files
#
# Generally package vulnerabilites listed in the ignore-vulnerabilities
# list below are there because:
# 1. There is no release that resolves the vulnerability.  In this case, there
#    should also be an expire entry to remind the pywbem team to recheck
# 2. The required version of a package to resolve the issue is not available
#    for all of the python version supported by pywbem. In that case, the
#    vulnerability will remain ignored until such time as the versions of
#    python that cannot support the required version of the package are no
#    longer supported by pywbem.

# Configuration for the 'safety scan' command
version: '3.0'

scanning-settings:
  max-depth: 1
  exclude:
    - requirements.txt
  include-files:
    - path: minimum-constraints-develop.txt
      file-type: requirements.txt
  system:
    targets: []

report:
  dependency-vulnerabilities:
    enabled: true
    auto-ignore-in-report:
      python:

        # Ignore dependencies found in the current Python environment
        environment-results: false

        # Ignore unpinned packages in requirements files
        unpinned-requirements: false

      cvss-severity: []

      # List of specific vulnerabilities to ignore.
      # {id}:                 # vulnerability ID
      #     reason: {text}    # Reason for ignoring it
      #     expires: {date}   # Date when this ignore will expire
      vulnerabilities:
        51457:
          reason: Py package is no longer being fixed (latest version 1.11.0)
          expires: '2099-01-01'
        70612:
          reason: Safety issue and CVE do not list a fixed version of Jinja2
          expires: '2099-01-01'
        71199:
          reason: Fixed anyio version 4.13.0 requires Python>=3.10 and is used there
          expires: '2099-01-01'
        79993:
          reason: Fixed jupyterlab version 4.4.8 requires Python>=3.9 and other upgrades
          expires: '2099-01-01'
        82754:
          reason: Fixed filelock version 3.20.1 requires Python>=3.10 and is used there
          expires: '2099-01-01'
        83159:
          reason: Fixed marshmallow version 4.3.0 requires Python>=3.10 and is used there
          expires: '2099-01-01'
        84183:
          reason: Fixed filelock version 3.20.3 requires Python>=3.10 and is used there
          expires: '2099-01-01'
        84415:
          reason: Fixed filelock version 3.20.3 requires Python>=3.10 and is used there
          expires: '2099-01-01'
        SFTY-20260218-01424:
          reason: Fixed nltk version 3.9.3 requires Python>=3.10 and is used there
          expires: '2099-01-01'
        SFTY-20260318-30374:
          reason: Fixed nltk version 3.9.3 requires Python>=3.10 and is used there
          expires: '2099-01-01'

fail-scan-with-exit-code:
  dependency-vulnerabilities:
    enabled: true
    fail-on-any-of:
      cvss-severity:
        - high
        - critical
        - medium
        - low
      exploitability:
        - high
        - critical
        - medium
        - low

security-updates:
  dependency-vulnerabilities:
    auto-security-updates-limit:
      - patch

installation:
  default-action: allow
  audit-logging:
    enabled: true
  allow:
    packages: []
    vulnerabilities: {}
  deny:
    packages: {}
    vulnerabilities:
      warning-on-any-of:
        cvss-severity: []
      block-on-any-of:
        cvss-severity: []
