#!/usr/bin/env python
# -*- coding: utf-8 -*-
 
"""wbemcli script.

For details, see the `pywbem.wbemcli` module.
"""

import sys 
from pywbem.wbemcli import main
 
if __name__ == '__main__':
    rc = main()
    sys.exit(rc)
