class PyWBEM_Person : CIM_Person {
};

class PyWBEM_PersonCollection : CIM_ConcreteCollection {
};

class PyWBEM_MemberOfPersonCollection : CIM_MemberOfCollection {
};

instance of PyWBEM_Person as $Alice {
	CreationClassName = "PyWBEM_Person";
	Name = "Alice";
};

instance of PyWBEM_Person as $Bob {
	CreationClassName = "PyWBEM_Person";
	Name = "Bob";
};

instance of PyWBEM_Person as $Charlie {
	CreationClassName = "PyWBEM_Person";
	Name = "Charlie";
};

instance of PyWBEM_PersonCollection as $Collection {
	InstanceID = "PersonCollection";
};

instance of PyWBEM_MemberOfPersonCollection {
	Collection = $Collection;
	Member = $Alice;
};

instance of PyWBEM_MemberOfPersonCollection {
	Collection = $Collection;
	Member = $Bob;
};

instance of PyWBEM_MemberOfPersonCollection {
	Collection = $Collection;
	Member = $Charlie;
};
