// ==================================================================
// Novell_DHCPSubnetInfo
// ==================================================================
[Description (
	"The Novell_DHCPSubnetInfo class represents the subnet information "
	"that the DHCP server is currently configured to support and service.")]
class Novell_DHCPSubnetInfo
{
	[Key, Description("The subnet address.")]
	string Subnet;

	[Description("Subnet netmask.")]
	string Netmask;

	[Description("IP address range start")]
	string IPRangeStart;

	[Description("IP address range end")]
	string IPRangeEnd;

	[Description("Router address.")]
	string Router;

	[Description ("Number of defined IP's in the range" }]
	uint16 DefinedIPs;
    // Error is extra } above

	[Description("Number of used IP's in the range")]
	uint16 UsedIPs;

	[Description("Number of free IP's in the range")]
	uint16 FreeIPs;
};

